# Generated by Django 3.2.9 on 2021-12-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_chatapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatApp',
        ),
    ]
