# Generated by Django 4.0 on 2021-12-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_newchatapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewChatApp',
        ),
    ]
